# SITE CONFIGURATION
baseurl: ""
url: "https://engineer.john-whittington.co.uk/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: John Whittington's Blog
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "Engineer John Whittington's personal project blog" # used by search engines

  # Header and footer text
  header_text:
  header_text_feature_image:
  footer_text: true

  # Icons
  rss: true
  email_address: j+blog@john-whittington.co.uk
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "tuna-f1sh"
  gitter:
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/jwilliamwhittington/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube: "@johnwhittington"

  # Scripts
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

imageoptim:
  verbose: true
  svgo: false

# PAGINATION
paginate: 14
paginate_path: "blog/:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-loading-lazy]

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;" # https://bendodson.com/weblog/2016/01/11/fixing-emoji-footnote-arrow-in-jekyll/

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - LICENSE
  - .env
  - Makefile
  - _compress_images_cache.yml
